server:
  port: 9998
thymeleaf:
  prefix:
    classpath: /templates/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sahara?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml